/* =====================================================================
   SERRES DRIVE — Fleet dataset
   The live fleet of our partner Sicurcars (sicurcars.es/nuestra-flota),
   scraped 2026-07-20. Prices mirror theirs exactly, in EUR:
     d1 = 1 día · w1 = 1 semana · d15 = 15 días · m1 = 1 mes
   Any of those keys may be ABSENT when Sicurcars does not publish that
   rate — render "Consúltanos" rather than assuming a number exists.
   Photos: assets/img/cars/<slug>.jpg (cards/hero) and
           assets/img/cars/ring/<slug>.jpg (3D tube tiles).
   ===================================================================== */
window.SERRES_FLEET = [
  {slug:"ferrari-458-spider",name:"Ferrari 458 Spider",brand:"Ferrari",category:"Descapotable",typeKey:"Convertible",bodyType:"Cabriolet",year:2021,powerCv:570,zeroToHundred:"3,4 s",topSpeed:"320 km/h",transmission:"F1 DCT 7 vel.",drivetrain:"RWD",seats:2,luggage:2,km:6100,fuel:"Gasolina",accent:"#cf2318",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"V8 atmosférico de 9.000 vueltas y cielo abierto: el último Ferrari que canta sin ayuda de turbos.",
   taglineEn:"A naturally aspirated V8 to nine thousand revs, open sky above, the last Ferrari that sings without turbochargers.",
   highlightsEs:["570 CV V8 atmosférico","Techo duro retráctil","Propulsión trasera F1 DCT"],
   highlightsEn:["570 hp naturally aspirated","Retractable hardtop","Rear-drive, F1 DCT"],
   prices:{d1:3900}},

  {slug:"mercedes-amg-g63",name:"Mercedes-AMG G 63",brand:"Mercedes-Benz",category:"SUV",typeKey:"SUV",bodyType:"SUV",year:2022,powerCv:585,zeroToHundred:"4,5 s",topSpeed:"220 km/h",transmission:"AMG TCT 9 vel.",drivetrain:"AWD",seats:5,luggage:6,km:7700,fuel:"Gasolina",accent:"#E85A1A",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un icono militar reinterpretado en clave AMG: 585 caballos que atraviesan la ciudad con presencia inconfundible.",
   taglineEn:"A military silhouette rewritten by AMG: 585 horsepower moving through the city with deliberate, unmistakable presence.",
   highlightsEs:["585 CV V8 biturbo","Tracción integral permanente","Icono todoterreno AMG"],
   highlightsEn:["585 hp biturbo V8","Permanent all-wheel drive","AMG off-road icon"],
   prices:{d1:2900}},

  {slug:"ferrari-f8-spider",name:"Ferrari F8 Spider",brand:"Ferrari",category:"Descapotable",typeKey:"Convertible",bodyType:"Cabriolet",year:2021,powerCv:720,zeroToHundred:"2,9 s",topSpeed:"340 km/h",transmission:"F1 DCT 7 vel.",drivetrain:"RWD",seats:2,luggage:2,km:15000,fuel:"Gasolina",accent:"#bb1a21",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Techo retráctil en catorce segundos y un V8 de 720 CV que firma la costa catalana",
   taglineEn:"Fourteen seconds of roof, then 720 CV of twin-turbo V8 signing its name along the coast",
   highlightsEs:["720 CV V8 biturbo","Propulsión trasera","Techo rígido retráctil"],
   highlightsEn:["720 hp twin-turbo V8","Rear-wheel drive","Retractable hardtop roof"],
   prices:{d1:1200,w1:6500,d15:6500,m1:14000}},

  {slug:"ferrari-488-gtb",name:"Ferrari 488 GTB",brand:"Ferrari",category:"Deportivo",typeKey:"Sports",bodyType:"Coupé",year:2020,powerCv:670,zeroToHundred:"3,0 s",topSpeed:"330 km/h",transmission:"F1 DCT 7 vel.",drivetrain:"RWD",seats:2,luggage:2,km:18000,fuel:"Gasolina",accent:"#d61c17",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Seiscientos setenta caballos detrás de la nuca y un V8 que aún suena a Maranello puro.",
   taglineEn:"Six hundred and seventy horses behind your shoulders and a V8 that still speaks pure Maranello.",
   highlightsEs:["670 CV V8 biturbo","0-100 en 3,0 s","Motor central trasero"],
   highlightsEn:["670 hp twin-turbo V8","0-100 in 3.0 s","Mid-engined layout"],
   prices:{d1:1200,w1:7000,m1:15000}},

  {slug:"mercedes-amg-g63-plus",name:"Mercedes-AMG G63 Plus",brand:"Mercedes-Benz",category:"Lujo",typeKey:"Luxury",bodyType:"SUV",year:2023,powerCv:585,zeroToHundred:"4,5 s",topSpeed:"220 km/h",transmission:"AMG Speedshift TCT 9 vel.",drivetrain:"AWD",seats:5,luggage:5,km:25000,fuel:"Gasolina",accent:"#1c1d20",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un icono militar reinterpretado en clave de lujo, con 585 CV que imponen respeto en cada semáforo",
   taglineEn:"A military silhouette turned object of desire, carrying 585 metric horses with unapologetic presence through the city",
   highlightsEs:["585 CV V8 biturbo","Tracción integral permanente","Tres bloqueos diferenciales"],
   highlightsEn:["585 hp twin-turbo V8","Permanent all-wheel drive","Three locking differentials"],
   prices:{d1:1000,w1:6000,d15:9000,m1:12000}},

  {slug:"mclaren-570s-gt",name:"McLaren 570S",brand:"McLaren",category:"Deportivo",typeKey:"Sports",bodyType:"Coupé",year:2022,powerCv:570,zeroToHundred:"3,4 s",topSpeed:"328 km/h",transmission:"SSG 7 vel.",drivetrain:"RWD",seats:2,luggage:2,km:15000,fuel:"Gasolina",accent:"#ef8022",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Fibra de carbono, motor central y 570 CV con la compostura suficiente para cruzar Europa sin pedir tregua.",
   taglineEn:"Carbon tub, mid-mounted V8, 570 horsepower and just enough civility to cross a continent.",
   highlightsEs:["570 CV V8 biturbo","Motor central trasero","Chasis monocasco carbono"],
   highlightsEn:["570 hp twin-turbo V8","Mid-engined layout","Carbon MonoCell chassis"],
   prices:{d1:900,w1:4550,m1:12000}},

  {slug:"porsche-911-targa-gts",name:"Porsche 911 Targa GTS",brand:"Porsche",category:"Deportivo",typeKey:"Sports",bodyType:"Cabriolet",year:2024,powerCv:480,zeroToHundred:"3,7 s",topSpeed:"307 km/h",transmission:"PDK 8 vel.",drivetrain:"AWD",seats:4,luggage:2,km:13000,fuel:"Gasolina",accent:"#1a2033",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"El arco de acero del Targa enmarca un bóxer de 480 CV y una tarde sin prisa.",
   taglineEn:"The Targa's steel hoop frames 480 horses and an afternoon that refuses to be rushed.",
   highlightsEs:["480 CV bóxer turbo","Tracción total 4","Arco Targa icónico"],
   highlightsEn:["480 hp turbo flat-six","All-wheel drive","Iconic Targa bar"],
   prices:{d1:800,w1:4200,m1:8010}},

  {slug:"aston-martin-dbx-707",name:"Aston Martin DBX 707",brand:"Aston Martin",category:"SUV",typeKey:"SUV",bodyType:"SUV",year:2023,powerCv:707,zeroToHundred:"3,3 s",topSpeed:"310 km/h",transmission:"Automático 9 vel.",drivetrain:"AWD",seats:5,luggage:5,km:20000,fuel:"Gasolina",accent:"#d2d6d7",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"El SUV más potente de Gaydon: 707 CV de V8 británico envueltos en cuero y calma.",
   taglineEn:"Gaydon's most powerful SUV: seven hundred horsepower wrapped in leather, restraint and impeccable British manners.",
   highlightsEs:["707 CV V8 biturbo","310 km/h punta","Frenos carbocerámicos de serie"],
   highlightsEn:["707 hp twin-turbo V8","310 km/h top speed","Standard carbon-ceramic brakes"],
   prices:{d1:800,w1:3500,m1:9000}},

  {slug:"bmw-m8-competition-cabrio",name:"BMW M8 Competition Cabrio",brand:"BMW",category:"Descapotable",typeKey:"Convertible",bodyType:"Cabriolet",year:2022,powerCv:625,zeroToHundred:"3,3 s",topSpeed:"305 km/h",transmission:"M Steptronic 8 vel.",drivetrain:"AWD",seats:4,luggage:2,km:22000,fuel:"Gasolina",accent:"#8e1f1c",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Seiscientos veinticinco caballos bajo cielo abierto, con la compostura suficiente para cruzar Europa sin despeinar a nadie.",
   taglineEn:"Six hundred and twenty-five horses under open sky, composed enough to cross a continent without raising its voice.",
   highlightsEs:["625 CV V8 biturbo","M xDrive conmutable","Capota de lona"],
   highlightsEn:["625 hp twin-turbo V8","Switchable M xDrive","Fabric soft top"],
   prices:{d1:700,w1:3500,m1:7500}},

  {slug:"porsche-911-carrera-992",name:"Porsche 911 Carrera (992)",brand:"Porsche",category:"Lujo",typeKey:"Luxury",bodyType:"Coupé",year:2024,powerCv:385,zeroToHundred:"4,2 s",topSpeed:"293 km/h",transmission:"PDK 8 vel.",drivetrain:"RWD",seats:2,luggage:3,km:5500,fuel:"Gasolina",accent:"#1b2f7a",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Bóxer trasero, chasis 992 y una compostura serena: el deportivo que se conduce igual de bien cada día.",
   taglineEn:"Rear-mounted flat-six, 992 chassis, quiet composure: the sports car that behaves as well on Tuesday as on Sunday.",
   highlightsEs:["385 CV bóxer biturbo","PDK 8 velocidades","Propulsión trasera"],
   highlightsEn:["385 hp twin-turbo flat-six","8-speed PDK","Rear-wheel drive"],
   prices:{d1:700,w1:4500,d15:3600,m1:9000}},

  {slug:"lamborghini-urus",name:"Lamborghini Urus",brand:"Lamborghini",category:"SUV",typeKey:"SUV",bodyType:"SUV Coupé",year:2024,powerCv:650,zeroToHundred:"3,6 s",topSpeed:"305 km/h",transmission:"Automático 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:18000,fuel:"Gasolina",accent:"#e2521c",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un superdeportivo que acepta equipaje, con 650 CV de V8 biturbo dispuestos a devorar la autopista",
   taglineEn:"The supercar that carries luggage, 650 CV of twin-turbo V8 flattening motorways with effortless authority",
   highlightsEs:["650 CV V8 biturbo","Tracción integral vectorial","0-100 en 3,6 s"],
   highlightsEn:["650 hp twin-turbo V8","Torque-vectoring all-wheel drive","0-100 in 3.6s"],
   prices:{d15:10000,m1:15000}},

  {slug:"ferrari-portofino-m",name:"Ferrari Portofino M",brand:"Ferrari",category:"Descapotable",typeKey:"Convertible",bodyType:"Cabriolet",year:2022,powerCv:620,zeroToHundred:"3,45 s",topSpeed:"320 km/h",transmission:"F1 DCT 8 vel.",drivetrain:"RWD",seats:4,luggage:2,km:16000,fuel:"Gasolina",accent:"#b01620",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Techo abatible en catorce segundos, seiscientos veinte caballos esperando detrás: la Costa Brava nunca estuvo tan cerca.",
   taglineEn:"Fourteen seconds of roof, six hundred and twenty horses waiting behind, and the coast road opens up.",
   highlightsEs:["620 CV V8 biturbo","Techo rígido retráctil","Propulsión trasera"],
   highlightsEn:["620 hp twin-turbo V8","Retractable hardtop roof","Rear-wheel drive"],
   prices:{d15:9000,m1:14000}},

  {slug:"porsche-cayenne-turbo-gt",name:"Porsche Cayenne Turbo GT",brand:"Porsche",category:"SUV",typeKey:"SUV",bodyType:"SUV Coupé",year:2024,powerCv:660,zeroToHundred:"3,3 s",topSpeed:"305 km/h",transmission:"Tiptronic S 8 vel.",drivetrain:"AWD",seats:4,luggage:5,km:16000,fuel:"Gasolina",accent:"#14243a",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"660 CV y una puesta a punto de circuito: el SUV que se comporta como un deportivo puro.",
   taglineEn:"Six hundred and sixty horsepower, chassis tuned at the Nürburgring: an SUV that behaves like a coupé.",
   highlightsEs:["660 CV V8 biturbo","0-100 en 3,3 s","Chasis afinado Nürburgring"],
   highlightsEn:["660 hp twin-turbo V8","0-100 in 3.3s","Nürburgring-tuned chassis"],
   prices:{d1:600,w1:2800,d15:4000,m1:7000}},

  {slug:"lamborghini-huracan-coupe",name:"Lamborghini Huracán Coupé",brand:"Lamborghini",category:"Deportivo",typeKey:"Sports",bodyType:"Coupé",year:2023,powerCv:640,zeroToHundred:"2,9 s",topSpeed:"325 km/h",transmission:"LDF doble embrague 7 vel.",drivetrain:"AWD",seats:2,luggage:2,km:12000,fuel:"Gasolina",accent:"#74b72e",featured:true,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Diez cilindros atmosféricos que suben hasta las 8.500 vueltas, la última ópera analógica firmada en Sant'Agata",
   taglineEn:"A naturally aspirated V10 singing to 8,500 rpm, the last analogue opera Sant'Agata will ever write",
   highlightsEs:["640 CV V10 atmosférico","Tracción integral variable","Doble embrague 7 vel."],
   highlightsEn:["640 hp V10","Variable all-wheel drive","Seven-speed dual clutch"],
   prices:{d15:9000,m1:13000}},

  {slug:"bmw-x7-m60i",name:"BMW X7 M60i",brand:"BMW",category:"Lujo",typeKey:"Luxury",bodyType:"SUV",year:2023,powerCv:530,zeroToHundred:"4,7 s",topSpeed:"250 km/h",transmission:"Steptronic 8 vel.",drivetrain:"AWD",seats:6,luggage:6,km:20000,fuel:"Híbrido ligero",accent:"#e8e6e1",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Seis plazas, ocho cilindros y un silencio de biblioteca hasta que el acelerador decide lo contrario.",
   taglineEn:"Six seats, eight cylinders and library silence, right up until the throttle decides otherwise on an open road.",
   highlightsEs:["530 CV V8 biturbo","Seis plazas individuales","Tracción total xDrive"],
   highlightsEn:["530 hp twin-turbo V8","Six individual seats","xDrive all-wheel drive"],
   prices:{d1:500,w1:2800,m1:5400}},

  {slug:"bmw-m4-competition",name:"BMW M4 Competition",brand:"BMW",category:"Lujo",typeKey:"Luxury",bodyType:"Coupé",year:2022,powerCv:510,zeroToHundred:"3,9 s",topSpeed:"250 km/h",transmission:"M Steptronic 8 vel.",drivetrain:"RWD",seats:4,luggage:3,km:22000,fuel:"Gasolina",accent:"#1c1d20",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Fibra de carbono, tracción trasera y un seis cilindros que respira rabia contenida entre curva y curva.",
   taglineEn:"Carbon shells, rear-drive purity and a straight-six that turns every apex into a controlled provocation.",
   highlightsEs:["510 CV biturbo","Tracción trasera pura","Butacas de carbono"],
   highlightsEn:["510 hp twin-turbo six","Pure rear-wheel drive","Carbon bucket seats"],
   prices:{d1:500,w1:2450,m1:6000}},

  {slug:"audi-rs6-avant",name:"Audi RS 6 Avant",brand:"Audi",category:"Deportivo",typeKey:"Sports",bodyType:"Familiar",year:2022,powerCv:600,zeroToHundred:"3,6 s",topSpeed:"280 km/h",transmission:"Tiptronic 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:25000,fuel:"Híbrido ligero",accent:"#6d7378",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un V8 biturbo de 600 CV escondido en el familiar más discreto y más rápido de Barcelona.",
   taglineEn:"Six hundred horsepower of twin-turbo V8 hidden inside the most understated estate on the road.",
   highlightsEs:["600 CV V8 biturbo","Tracción quattro permanente","Maletero de 565 litros"],
   highlightsEn:["600 hp twin-turbo V8","Full-time quattro drive","565-litre boot"],
   prices:{d1:500,w1:2800,m1:7500}},

  {slug:"alfa-romeo-stelvio-quadrifoglio",name:"Alfa Romeo Stelvio Quadrifoglio",brand:"Alfa Romeo",category:"SUV",typeKey:"SUV",bodyType:"SUV",year:2022,powerCv:510,zeroToHundred:"3,8 s",topSpeed:"283 km/h",transmission:"Automático ZF 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:30000,fuel:"Gasolina",accent:"#1a6fd0",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un V6 biturbo de origen Maranello convierte cada curva de la Costa Brava en una declaración italiana.",
   taglineEn:"A Maranello-bred twin-turbo V6 turns every coastal bend into an argument for Italian engineering.",
   highlightsEs:["510 CV V6 biturbo","Tracción Q4 integral","0-100 en 3,8 s"],
   highlightsEn:["510 hp twin-turbo V6","Q4 all-wheel drive","0-100 in 3.8 s"],
   prices:{d1:500,w1:2296,m1:4500}},

  {slug:"porsche-718-spyder",name:"Porsche 718 Spyder",brand:"Porsche",category:"Descapotable",typeKey:"Convertible",bodyType:"Roadster",year:2023,powerCv:420,zeroToHundred:"4,4 s",topSpeed:"301 km/h",transmission:"Manual 6 vel.",drivetrain:"RWD",seats:2,luggage:2,km:14000,fuel:"Gasolina",accent:"#e2e4e6",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Seis cilindros atmosféricos, capota manual y 420 CV: el purismo Porsche reducido a su forma más honesta.",
   taglineEn:"Naturally aspirated flat-six, a roof you fold by hand, and nothing between you and the road.",
   highlightsEs:["420 CV atmosférico","Manual seis marchas","Capota manual ligera"],
   highlightsEn:["420 hp naturally aspirated","Six-speed manual","Hand-folded soft top"],
   prices:{d1:450,w1:2000,d15:2500,m1:5500}},

  {slug:"audi-rs-q3",name:"Audi RS Q3",brand:"Audi",category:"SUV",typeKey:"SUV",bodyType:"SUV",year:2020,powerCv:400,zeroToHundred:"4,5 s",topSpeed:"250 km/h",transmission:"S tronic 7 vel.",drivetrain:"AWD",seats:5,luggage:6,km:4500,fuel:"Gasolina",accent:"#a9a8a4",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Cinco cilindros en línea con sonido inconfundible, tracción quattro y la compostura de un deportivo con altura.",
   taglineEn:"The five-cylinder howl of Ingolstadt's rally past, wrapped in a compact SUV that never loses composure.",
   highlightsEs:["400 CV cinco cilindros","Tracción quattro permanente","0-100 en 4,5 s"],
   highlightsEn:["400 hp five-cylinder","Permanent quattro traction","0-100 in 4.5 s"],
   prices:{d1:450,w1:2000,m1:5000}},

  {slug:"audi-rsq3-sportback",name:"Audi RS Q3 Sportback",brand:"Audi",category:"SUV",typeKey:"SUV",bodyType:"SUV Coupé",year:2024,powerCv:400,zeroToHundred:"4,5 s",topSpeed:"250 km/h",transmission:"S tronic 7 vel.",drivetrain:"AWD",seats:5,luggage:5,km:22000,fuel:"Gasolina",accent:"#191a1d",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Techo descendente, cinco cilindros y quattro: el SUV que se comporta como un coupé deportivo alemán.",
   taglineEn:"A falling roofline, five cylinders and quattro grip, the coupé that happens to seat five.",
   highlightsEs:["400 CV cinco cilindros","Carrocería coupé quattro","0-100 en 4,5 s"],
   highlightsEn:["400 hp five-cylinder","Coupé body, quattro drive","0-100 in 4.5 s"],
   prices:{d1:450,w1:2000,m1:5000}},

  {slug:"audi-rs3",name:"Audi RS 3",brand:"Audi",category:"Deportivo",typeKey:"Sports",bodyType:"Hatchback",year:2024,powerCv:400,zeroToHundred:"3,8 s",topSpeed:"250 km/h",transmission:"S tronic 7 vel.",drivetrain:"AWD",seats:5,luggage:3,km:18000,fuel:"Gasolina",accent:"#a8abac",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Cinco cilindros con voz propia, tracción quattro y una compostura que convierte cualquier ronda barcelonesa en trazada limpia.",
   taglineEn:"A five-cylinder voice like no other, quattro grip beneath, turning every Barcelona ring road into a clean line.",
   highlightsEs:["400 CV 5 cilindros","Tracción quattro","0-100 en 3,8 s"],
   highlightsEn:["400 hp five-cylinder","quattro all-wheel drive","0-100 in 3.8 s"],
   prices:{d1:450,w1:2000,m1:5000}},

  {slug:"mercedes-amg-a45-s",name:"Mercedes-AMG A45 S",brand:"Mercedes-Benz",category:"Deportivo",typeKey:"Sports",bodyType:"Hatchback",year:2023,powerCv:425,zeroToHundred:"3,9 s",topSpeed:"270 km/h",transmission:"AMG DCT 8 vel.",drivetrain:"AWD",seats:5,luggage:3,km:20000,fuel:"Gasolina",accent:"#6f7274",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"El compacto más intenso de Affalterbach: motor construido a mano, 4MATIC+ y una precisión que no admite discusión.",
   taglineEn:"Affalterbach's smallest statement: a hand-built four-cylinder, all-wheel traction and a sharpness that leaves nothing open to debate.",
   highlightsEs:["425 CV turbo","4MATIC+ con Drift Mode","Motor hecho a mano"],
   highlightsEn:["425 hp turbo four","4MATIC+ Drift Mode","Hand-built AMG engine"],
   prices:{d1:450,w1:2000,m1:5000}},

  {slug:"audi-rs4-avant",name:"Audi RS 4 Avant",brand:"Audi",category:"Deportivo",typeKey:"Sports",bodyType:"Familiar",year:2022,powerCv:450,zeroToHundred:"4,1 s",topSpeed:"280 km/h",transmission:"Tiptronic 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:25000,fuel:"Gasolina",accent:"#1c1d20",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"V6 biturbo, quattro y cinco plazas: la herramienta discreta para cruzar Cataluña sin levantar una sola ceja.",
   taglineEn:"Twin-turbo V6, quattro grip and five seats, the quiet way to cross a country quickly.",
   highlightsEs:["450 CV V6 biturbo","quattro con diferencial deportivo","Familiar de altas prestaciones"],
   highlightsEn:["450 hp twin-turbo V6","quattro sport differential","High-performance estate body"],
   prices:{d1:400,w1:2100,m1:5400}},

  {slug:"volkswagen-golf-r",name:"Volkswagen Golf R",brand:"Volkswagen",category:"Deportivo",typeKey:"Sports",bodyType:"Hatchback",year:2025,powerCv:333,zeroToHundred:"4,6 s",topSpeed:"250 km/h",transmission:"DSG 7 vel.",drivetrain:"AWD",seats:5,luggage:3,km:15000,fuel:"Gasolina",accent:"#1c1d20",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"333 caballos y tracción total bajo una carrocería que jamás delata lo que es capaz de hacer.",
   taglineEn:"All-wheel drive and 333 horsepower behind a shape that gives away nothing until the road opens.",
   highlightsEs:["333 CV 2.0 TSI","Tracción total 4MOTION","DSG 7 velocidades"],
   highlightsEn:["333 hp 2.0 TSI","4MOTION all-wheel drive","7-speed DSG"],
   prices:{d1:400,w1:1800,m1:4500}},

  {slug:"maserati-levante-gransport",name:"Maserati Levante GranSport",brand:"Maserati",category:"SUV",typeKey:"SUV",bodyType:"SUV",year:2022,powerCv:350,zeroToHundred:"6,0 s",topSpeed:"251 km/h",transmission:"Automático 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:30000,fuel:"Gasolina",accent:"#26242a",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"El trono italiano sobre ruedas altas, con temple de gran turismo, voz de V6 y tracción integral Q4",
   taglineEn:"Italian grand touring raised on stilts, with a twin-turbo V6 voice and all-weather Q4 composure beneath",
   highlightsEs:["350 CV V6 biturbo","Tracción integral Q4","Suspensión neumática adaptativa"],
   highlightsEn:["350 hp twin-turbo V6","Q4 all-wheel drive","Adaptive air suspension"],
   prices:{d1:300,w1:1540,m1:3600}},

  {slug:"audi-a5-avant",name:"Audi A5 Avant",brand:"Audi",category:"Lujo",typeKey:"Luxury",bodyType:"Familiar",year:2025,powerCv:204,zeroToHundred:"7,4 s",topSpeed:"240 km/h",transmission:"S tronic 7 vel.",drivetrain:"FWD",seats:5,luggage:5,km:10000,fuel:"Diésel",accent:"#7d919b",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Kilómetros largos en silencio: la elegancia serena de un Avant pensado para llegar descansado y sin ruido.",
   taglineEn:"Long, quiet kilometres in an estate built for arriving composed rather than for arriving first.",
   highlightsEs:["204 CV diésel MHEV","S tronic 7 vel.","Amplio maletero familiar"],
   highlightsEn:["204 hp mild-hybrid diesel","Seven-speed S tronic","Generous estate boot"],
   prices:{d1:300,w1:1800,m1:5000}},

  {slug:"porsche-cayenne-gts-coupe",name:"Porsche Cayenne GTS Coupé",brand:"Porsche",category:"SUV",typeKey:"SUV",bodyType:"SUV Coupé",year:2023,powerCv:460,zeroToHundred:"4,5 s",topSpeed:"275 km/h",transmission:"Tiptronic S 8 vel.",drivetrain:"AWD",seats:5,luggage:5,km:22000,fuel:"Gasolina",accent:"#cdcac3",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Un V8 de 460 CV bajo una silueta coupé que convierte cada trayecto por la costa en ceremonia.",
   taglineEn:"Four litres of V8 beneath a coupé roofline, turning the coast road into something closer to ritual.",
   highlightsEs:["460 CV V8 biturbo","Tracción integral","Escape deportivo GTS"],
   highlightsEn:["460 hp twin-turbo V8","All-wheel drive","GTS sports exhaust"],
   prices:{m1:5940}},

  {slug:"bmw-m135i-xdrive",name:"BMW M135i xDrive",brand:"BMW",category:"Deportivo",typeKey:"Sports",bodyType:"Hatchback",year:2023,powerCv:306,zeroToHundred:"4,8 s",topSpeed:"250 km/h",transmission:"Steptronic 8 vel.",drivetrain:"AWD",seats:5,luggage:3,km:18000,fuel:"Gasolina",accent:"#0d72c4",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Formato compacto, tracción total y trescientos seis caballos para el Garraf un domingo por la mañana.",
   taglineEn:"A compact body, all-wheel grip and three hundred and six horses aimed at an empty Sunday road.",
   highlightsEs:["306 CV turbo","Tracción total xDrive","0-100 en 4,8 s"],
   highlightsEn:["306 hp turbo four","xDrive all-wheel drive","0-100 in 4.8 s"],
   prices:{d1:250,w1:1400,m1:3500}},

  {slug:"mercedes-c220d-cabrio",name:"Mercedes C 220 d Cabrio",brand:"Mercedes-Benz",category:"Descapotable",typeKey:"Convertible",bodyType:"Cabriolet",year:2021,powerCv:194,zeroToHundred:"7,6 s",topSpeed:"236 km/h",transmission:"9G-TRONIC 9 vel.",drivetrain:"RWD",seats:4,luggage:2,km:4700,fuel:"Diésel",accent:"#1c1d20",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"Techo abierto sobre la costa del Maresme, con el silencio diésel y la autonomía para no mirar atrás.",
   taglineEn:"Roof down along the Maresme coast, quiet diesel torque and enough range to keep the return trip optional.",
   highlightsEs:["194 CV diésel","Capota lona 20 s","Airscarf y Aircap"],
   highlightsEn:["194 hp diesel","Fabric roof, 20 s","Airscarf neck warmer"],
   prices:{d1:250,w1:1400,m1:3500}},

  {slug:"abarth-595-competizione",name:"Abarth 595 Competizione",brand:"Abarth",category:"Deportivo",typeKey:"Sports",bodyType:"Hatchback",year:2020,powerCv:180,zeroToHundred:"6,7 s",topSpeed:"225 km/h",transmission:"Manual 5 vel.",drivetrain:"FWD",seats:4,luggage:1,km:20000,fuel:"Gasolina",accent:"#e5b117",featured:false,
   extras:["Bluetooth","Cruise Control","Built-in GPS","Rear Camera","Lane Assist","Auto Wipers","Wireless Charging","Sunroof","Apple CarPlay","Parking Sensors"],
   taglineEs:"El escorpión más pequeño de Turín: 180 caballos, escape Record Monza y un temperamento imposible de ignorar.",
   taglineEn:"Turin's smallest scorpion, all 180 horses of it, announcing itself through a Record Monza exhaust.",
   highlightsEs:["180 CV turbo","Escape Record Monza","Tracción delantera ágil"],
   highlightsEn:["180 hp turbo four","Record Monza exhaust","Agile front-wheel drive"],
   prices:{d1:120,w1:700,m1:1740}}
];

/* Category order + labels (ES/EN) for the filter bar. Mirrors the four
   "Tipo de coche" facets Sicurcars filters on. */
window.SERRES_CATEGORIES = [
  {key:"Todos",        en:"All"},
  {key:"Deportivo",    en:"Sports"},
  {key:"SUV",          en:"SUV"},
  {key:"Lujo",         en:"Luxury"},
  {key:"Descapotable", en:"Convertible"}
];
