/* =====================================================================
   SERRES DRIVE — dataset para la portada (hero 3D + tubo)
   GENERADO por _build/build-home-assets.js desde data/fleet.json.
   No editar a mano: el siguiente build lo pisa. Los precios viven en
   _build/fleet-base.json y de ahi bajan a data/fleet.json.

   Son los 13 coches REALES. La version anterior de este archivo tenia 31
   e incluia Ferrari, BMW, McLaren y demas, que ya no estan en la flota.
   ===================================================================== */
window.SERRES_RING_V = "fbc18739b8";
window.SERRES_FLEET = [
  {"slug":"mercedes-amg-g63","name":"Mercedes-AMG G 63","brand":"Mercedes-AMG","category":"SUV","bodyType":"SUV","powerCv":585,"zeroToHundred":"4,5 s","topSpeed":"220 km/h","transmission":"AMG TCT 9 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#b9bec9","featured":true,"taglineEs":"Tres bloqueos de diferencial y un V8 biturbo de 585 CV bajo la silueta que no cambia desde 1979.","highlightsEs":["585 CV V8 biturbo","0-100 en 4,5 s","Tres bloqueos de diferencial"],"prices":{"d1":1000,"d2":1700,"d3":2700,"w1":6000,"m1":12000},"deposit":5000,"url":"/coches/mercedes-amg-g63/"},
  {"slug":"lamborghini-urus","name":"Lamborghini Urus","brand":"Lamborghini","category":"SUV Coupé","bodyType":"SUV Coupé","powerCv":650,"zeroToHundred":"3,6 s","topSpeed":"305 km/h","transmission":"Automatico 8 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#f2c200","featured":true,"taglineEs":"Cinco plazas y 650 CV de V8 biturbo bajo una carrocería negra mate, con el amarillo reservado para el interior.","highlightsEs":["650 CV V8 biturbo","0-100 en 3,6 s","305 km/h, tracción integral"],"prices":{"d1":1100,"d2":1900,"d3":3000,"w1":6500,"m1":13000},"deposit":null,"url":"/coches/lamborghini-urus/"},
  {"slug":"audi-rs6-avant","name":"Audi RS 6 Avant","brand":"Audi","category":"Familiar","bodyType":"Familiar","powerCv":600,"zeroToHundred":"3,6 s","topSpeed":"280 km/h","transmission":"Tiptronic 8 vel.","drivetrain":"AWD","seats":5,"fuel":"Híbrido ligero","accent":"#c3c7d0","featured":true,"taglineEs":"Cinco plazas, maletero de familiar y un V8 biturbo de 600 CV que resuelve el 0-100 en 3,6 segundos.","highlightsEs":["600 CV V8 biturbo","0-100 en 3,6 s","Familiar quattro de 5 plazas"],"prices":{"d1":900,"d2":1600,"d3":2500,"w1":5500,"m1":11000},"deposit":null,"url":"/coches/audi-rs6-avant/"},
  {"slug":"porsche-911-cabrio","name":"Porsche 911 Cabrio (992)","brand":"Porsche","category":"Cabriolet","bodyType":"Cabriolet","powerCv":450,"zeroToHundred":"3,9 s","topSpeed":"306 km/h","transmission":"PDK 8 vel.","drivetrain":"RWD","seats":4,"fuel":"Gasolina","accent":"#c8ccd6","featured":true,"taglineEs":"Un bóxer bíturbo de 450 CV detrás de la nuca y una capota que se abre en doce segundos rodando.","highlightsEs":["450 CV bóxer bíturbo","Capota abierta en 12 s","306 km/h, tracción trasera"],"prices":{"d1":800,"d2":1500,"d3":2200,"w1":4600,"m1":9000},"deposit":2000,"url":"/coches/porsche-911-cabrio/"},
  {"slug":"porsche-911-carrera-s","name":"Porsche 911 Carrera S (991)","brand":"Porsche","category":"Coupé","bodyType":"Coupé","powerCv":400,"zeroToHundred":"4,3 s","topSpeed":"302 km/h","transmission":"PDK 7 vel.","drivetrain":"RWD","seats":4,"fuel":"Gasolina","accent":"#c8ccd6","featured":false,"taglineEs":"El último Carrera S atmosférico: un bóxer 3.8 que estira hasta las 7.400 rpm, PDK de siete marchas y techo solar.","highlightsEs":["400 CV atmosféricos a 7.400 rpm","0-100 km/h en 4,3 s","PDK 7 vel., propulsión trasera"],"prices":{"d1":700,"d2":1300,"d3":2000,"w1":3500,"m1":7500},"deposit":2000,"url":"/coches/porsche-911-carrera-s/"},
  {"slug":"porsche-cayenne-hybrid","name":"Porsche Cayenne Hybrid","brand":"Porsche","category":"SUV Coupé","bodyType":"SUV Coupé","powerCv":470,"zeroToHundred":"4,9 s","topSpeed":"254 km/h","transmission":"Tiptronic S 8 vel.","drivetrain":"AWD","seats":4,"fuel":"Híbrido enchufable","accent":"#c8ccd6","featured":true,"taglineEs":"Gris tiza por fuera, cuero rojo por dentro: 470 CV que salen del párking en silencio eléctrico y firman 4,9 segundos.","highlightsEs":["470 CV híbrido enchufable","0-100 en 4,9 s","Modo eléctrico puro en ciudad"],"prices":{"d1":700,"d2":1300,"d3":2000,"w1":3500,"m1":7500},"deposit":2000,"url":"/coches/porsche-cayenne-hybrid/"},
  {"slug":"mercedes-amg-a45","name":"Mercedes-AMG A45 S","brand":"Mercedes-AMG","category":"Hatchback","bodyType":"Hatchback","powerCv":421,"zeroToHundred":"3,9 s","topSpeed":"270 km/h","transmission":"AMG SPEEDSHIFT DCT 8 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#b9bec9","featured":false,"taglineEs":"Un compacto de cinco plazas con el cuatro cilindros montado a mano en Affalterbach: 421 CV y 3,9 segundos.","highlightsEs":["421 CV y 500 Nm","0-100 en 3,9 s","Tracción total AMG 4MATIC+"],"prices":{"d1":450,"d2":800,"d3":1100,"w1":2000,"m1":5000},"deposit":2000,"url":"/coches/mercedes-amg-a45/"},
  {"slug":"audi-rs3-sportback","name":"Audi RS 3 Sportback","brand":"Audi","category":"Hatchback","bodyType":"Hatchback","powerCv":400,"zeroToHundred":"3,8 s","topSpeed":"250 km/h","transmission":"S tronic 7 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#c3c7d0","featured":false,"taglineEs":"El cinco cilindros en línea suena como ningún otro compacto: 400 CV, torque splitter trasero y 3,8 segundos hasta los 100.","highlightsEs":["400 CV 5 cilindros TFSI","0-100 en 3,8 s","quattro con torque splitter"],"prices":{"d1":450,"d2":800,"d3":1100,"w1":2000,"m1":5000},"deposit":2000,"url":"/coches/audi-rs3-sportback/"},
  {"slug":"audi-rsq3","name":"Audi RS Q3","brand":"Audi","category":"SUV","bodyType":"SUV","powerCv":400,"zeroToHundred":"4,5 s","topSpeed":"250 km/h","transmission":"S tronic 7 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#c3c7d0","featured":false,"taglineEs":"Orden de encendido 1-2-4-5-3: el cinco cilindros 2.5 TFSI lleva 400 CV al quattro y firma el 0-100 en 4,5 segundos.","highlightsEs":["400 CV 2.5 TFSI","0-100 en 4,5 s","Tracción quattro permanente"],"prices":{"d1":450,"d2":800,"d3":1100,"w1":2000,"m1":5000},"deposit":2000,"url":"/coches/audi-rsq3/"},
  {"slug":"volkswagen-golf-r","name":"Volkswagen Golf 8.5 R","brand":"Volkswagen","category":"Hatchback","bodyType":"Hatchback","powerCv":333,"zeroToHundred":"4,6 s","topSpeed":"250 km/h","transmission":"DSG 7 vel.","drivetrain":"AWD","seats":5,"fuel":"Gasolina","accent":"#aeb6c4","featured":false,"taglineEs":"Un compacto de cinco plazas con 420 Nm, frenos de altas prestaciones y modo Race escondidos bajo una carrocería negra.","highlightsEs":["333 CV y 420 Nm","0-100 en 4,6 s","4MOTION con vectorización de par"],"prices":{"d1":400,"d2":750,"d3":1000,"w1":1800,"m1":4500},"deposit":2000,"url":"/coches/volkswagen-golf-r/"},
  {"slug":"range-rover-velar","name":"Range Rover Velar","brand":"Range Rover","category":"SUV","bodyType":"SUV","powerCv":204,"zeroToHundred":"8,3 s","topSpeed":"210 km/h","transmission":"Automática 8 vel.","drivetrain":"AWD","seats":5,"fuel":"Híbrido ligero","accent":"#9fb0ad","featured":false,"taglineEs":"Manillas enrasadas, azul profundo y cuero caramelo: el Velar D200 mueve sus 430 Nm por Barcelona sin levantar la voz.","highlightsEs":["204 CV diésel microhíbrido","430 Nm y tracción total","Maletero de 568 litros"],"prices":{"d1":350,"d2":700,"d3":900,"w1":1800,"m1":4300},"deposit":2000,"url":"/coches/range-rover-velar/"},
  {"slug":"mercedes-glc","name":"Mercedes GLC","brand":"Mercedes-Benz","category":"SUV","bodyType":"SUV","powerCv":258,"zeroToHundred":"6,2 s","topSpeed":"240 km/h","transmission":"9G-TRONIC 9 vel.","drivetrain":"AWD","seats":5,"fuel":"Híbrido ligero","accent":"#b9bec9","featured":false,"taglineEs":"Negro AMG Line sobre cuero claro: 258 CV con apoyo eléctrico de 48 voltios y tracción 4MATIC permanente.","highlightsEs":["258 CV con hibridación 48V","0-100 km/h en 6,2 s","AMG Line, cuero claro"],"prices":{"d1":200,"d2":350,"d3":550,"w1":1000,"m1":2500},"deposit":2000,"url":"/coches/mercedes-glc/"},
  {"slug":"mercedes-a200-4matic","name":"Mercedes A200 4Matic","brand":"Mercedes-Benz","category":"Hatchback","bodyType":"Hatchback","powerCv":163,"zeroToHundred":"8,2 s","topSpeed":"225 km/h","transmission":"7G-DCT 7 vel.","drivetrain":"AWD","seats":5,"fuel":"Híbrido ligero","accent":"#b9bec9","featured":false,"taglineEs":"El compacto de Mercedes con 163 CV microhibridados, cambio 7G-DCT de doble embrague y acabado AMG Line en blanco.","highlightsEs":["163 CV con microhibridación","0-100 en 8,2 s","Pack AMG Line, 5 plazas"],"prices":{"d1":150,"d2":250,"d3":400,"w1":900,"m1":1800},"deposit":2000,"url":"/coches/mercedes-a200-4matic/"}
];
